### ISSUE TITLE
Some errors with getAllUserNFTs func on localhost

### ISSUE THREAD

**Issue by progforyou** [Psychedelic/dab#39]
Hello, dab 0.4.4 has some errors with getAllUserNFTs func. In your file nfts_refistry.js this principal not work with plug principal. But if call with string, it work with errors.
`const userPrincipal = user instanceof principal_1.Principal ? user : principal_1.Principal.fromText(user);`
![50 errors stack](https://user-images.githubusercontent.com/97514985/149291676-2fea80be-0031-4255-b692-2d3e5d409648.png)
please, help with this problem
```
const result = await window.ic.plug.getPrincipal();
const collections = await getAllUserNFTs(
            {user: principal.toString()}
        );
```
`"@psychedelic/dab-js": "^0.4.4",`
p.s. with stoic same error

**Comment by Nima-Ra** [comment]
Hi! This is an issue related to the DAB js library. This repository is about dab canisters. Create an issue in the dab js repository, please :)
https://github.com/Psychedelic/DAB-js
