### ISSUE TITLE
Add NFT to DAB

### ISSUE THREAD

**Issue by Jyy10** [Psychedelic/dab#83]
Hello, I would like to add our NFT to DAB. However, https://dab-ooo.typeform.com/nft-list is not accessible.

**Comment by panch8** [comment]
also happens whe trying to submit a token. any walkaround?

**Comment by EmperorOrokuSaki** [comment]
Hi @Jyy10 and @panch8 !
I recommend you to message the twitter page of DAB about this. Since the ownership of the product was transferred, I have not been involved in its maintenance.

**Comment by panch8** [comment]
@EmperorOrokuSaki  do you have handy their twitter handle?

**Comment by EmperorOrokuSaki** [comment]
> @EmperorOrokuSaki  do you have handy their twitter handle?

Yes its dab_ooo
